[build]
  base = "menswear-web"
  command = "npm install --no-audit --no-fund && npm run build"
  publish = ".next"

  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
